### ISSUE TITLE
CallbackReturn should not be a type

### ISSUE THREAD

**Issue by thelink2012** [dcampbell24/rust-iup-sys#1]
Instead it's values should be `c_int` constants.

This is a thing because you indeed can return arbitrary values from the callback, for example the ACTION callback of [`IupText`](http://webserver2.tecgraf.puc-rio.br/iup/en/elem/iuptext.html) is allowed to return a character value.

**Comment by dcampbell24** [comment]
OK, feel free to make the change and I can bump the version and publish or you can if you want to be a co-owner of the package.
