### ISSUE TITLE
Upgrade to IUP 3.14?

### ISSUE THREAD

**Issue by abonander** [dcampbell24/rust-iup-sys#2]
I see the version in `lib.rs` is declared as 3.12. Is there any issue with linking with 3.14? I'm instructing my KISS-UI users to link to that version.

**Comment by thelink2012** [comment]
Yep there's no issue with linking with 3.14, it is binary compatible.

From looking in the [change history](http://webserver2.tecgraf.puc-rio.br/iup/en/history3.html) all the binary breaking changes happend either on Plot or Matrix libraries.

The only thing that needs to be added here to be as 3.14 seems to be

> New: IupParamf and IupParamBox utility functions, exported from IupGetParam internals.
